version: '3.9'

services:
  app:
    image: node:alpine
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${CONFIG_MONGODB_URL}
    command: > 
      sh -c "npm install && npm run start"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH: false
